### ISSUE TITLE
Lembrar de manter a linguagem do repositório

### ISSUE THREAD

**Issue by panoramix360** [jpeedroza/Renatinho-Calculator#2]
Lembrem-se sempre de manter a linguagem que está sendo utilizada no repositório que vocês estiverem trabalhando.

Ex.: Se o projeto estiver em PT-BR, tentem commitar sempre em PT-BR

**Comment by jpeedroza** [comment]
@panoramix360 Fiz a correção dos commits dando um rebase em todos eles, porém os commits "errados" persistiram. Teria algum jeito de apagar os commits incorretos e deixar somente os que dei rebase ?
Os commits ficaram dessa forma
<img width="832" alt="Screen Shot 2021-04-23 at 15 43 07" src="https://user-images.githubusercontent.com/67215104/115916039-9b00fb00-a44a-11eb-84b3-e476dbcdc434.png">

**Comment by panoramix360** [comment]
Pode deixar os commits incorretos, sem problema, tenta manter o padrão para os próximos :)
