### ISSUE TITLE
Commit inicial muito grande

### ISSUE THREAD

**Issue by panoramix360** [jpeedroza/Renatinho-Calculator#4]
Cuidado com commits muito grandes no projeto, principalmente os iniciais, o ideal é fazer apenas um scaffolding inicial e ir preenchendo com funcionalidade depois

**Comment by jpeedroza** [comment]
@panoramix360 O commit acabou ficando grande por conta de um erro meu de dar push force na master, e acabou sumindo todos os commits anteriores.

**Comment by panoramix360** [comment]
@jpeedroza ah beleza, sem problemas! a issue foi só pra levantar um ponto de atenção mesmo
