### ISSUE TITLE
Criar Enums para operações

### ISSUE THREAD

**Issue by panoramix360** [jpeedroza/Renatinho-Calculator#6]
Na Classe App.java, vocês utilizaram apenas números para separar as operações.

Seria legal criar Enums para cada operação para que o código fique mais legível entre qual operação é qual.

**Comment by jpeedroza** [comment]
Invés de criar um Enum cobrindo todas as operações, fiz um HashMap contendo todas elas que facilitaria na redução do loop do main citado na issue #3 .

**Comment by panoramix360** [comment]
Beleza, lembra de sempre referenciar a Issue ao commitar
