### ISSUE TITLE
Inserir versão do Java

### ISSUE THREAD

**Issue by panoramix360** [jpeedroza/Renatinho-Calculator#7]
No README.md do projeto não possui a informação de qual a versão do Java que foi utilizada no desenvolvimento.

O ideal para que não possua erros ao utilziar versões mais antigas ou mais novas

**Comment by jpeedroza** [comment]
Issue resolvida no PR #10

**Comment by marciosamuel** [comment]
@panoramix360 Concluído (eu acho)

**Comment by panoramix360** [comment]
Está sim! boa!
