### ISSUE TITLE
Pasta run com arquivos .class

### ISSUE THREAD

**Issue by panoramix360** [jpeedroza/Renatinho-Calculator#8]
Cuidado ao commitar arquivos .class já que é um arquivo em bytecode.

O ideal é colocar um .gitignore

**Comment by jpeedroza** [comment]
Issue resolvida nos PR #9 e #12

**Comment by marciosamuel** [comment]
@panoramix360 Tá tudo certo?

**Comment by panoramix360** [comment]
Está sim, vou fechar a issue!
